services:
  media-converter:
    build: .
    container_name: media_converter_pro
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /mnt/media-converter/media/inputs:/media/inputs
      - /mnt/media-converter/media/outputs:/media/outputs
      - ./config:/app/config
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
